### ISSUE TITLE
Edit - Cancel deletes the text

### ISSUE THREAD

**Issue by michefraim** [danieleliyho/pre-course-2021-final-boilerplate#1]
When ever i try to edit a task, if i just press cancel the text of that task just disappears.

**Steps to reproduce:**

1. create/have a task.
2. press the Edit button on that task
3. press cancel on the prompt

**Expected results:**
Nothing should change

**Actual results:**
The task text disappears.

**Comment by danieleliyahu** [comment]
thank you i fix it :)
