### ISSUE TITLE
Selecting a task as done line-through the edit and remove buttons.

### ISSUE THREAD

**Issue by michefraim** [danieleliyho/pre-course-2021-final-boilerplate#3]
Whenever i select a task as done (using the checkbox) the same task Edit and Remove buttons get a line-through.

**Steps to reproduce:**

1. create/have a task
2. check it as done (using the checkbox)

**Expected result:**
line-through the text of the task only.

**Actual result:**
line through the whole task including the Edit and Remove button

**Comment by danieleliyahu** [comment]
I fix it thanks
