### ISSUE TITLE
search button

### ISSUE THREAD

**Issue by shirameirovitz** [danieleliyho/pre-course-2021-final-boilerplate#4]
When adding a text to search and clicking on the add task input after that: the search input does not clear itself automatically.
Steps to reproduce:
1. add text to the search input.
2. go to the add task input and click.
3. add text that is different from the text that is in the search input.
4. click on the add button.
expected result:
1. the search input will clear itself automatically when clicking on the add input.
2. see new task when you click on the adding button

actual result
cant see the new task because the search input still has text in it.

**Comment by danieleliyahu** [comment]
thank I solve the problem
